apiVersion: v1
entries:
  postgres-operator:
  - apiVersion: v1
    appVersion: 1.7.0
    created: "2021-08-27T10:21:42.643185124+02:00"
    description: Postgres Operator creates and manages PostgreSQL clusters running in Kubernetes
    digest: 1c4a1d289188ef72e409892fd2b86c008a37420af04a9796a8829ff84ab09e61
    home: https://github.com/zalando/postgres-operator
    keywords:
    - postgres
    - operator
    - cloud-native
    - patroni
    - spilo
    maintainers:
    - email: opensource@zalando.de
      name: Zalando
    name: postgres-operator
    sources:
    - https://github.com/zalando/postgres-operator
    urls:
    - postgres-operator-1.7.0.tgz
    version: 1.7.0
generated: "2021-08-27T10:21:42.631372502+02:00"
